defmodule Terrible.Repo.Migrations.CreateCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text, null: false

      add :book_id,
          references(:books,
            column: :id,
            name: "categories_book_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:categories, ["book_id"])
  end

  def down do
    drop constraint(:categories, "categories_book_id_fkey")

    drop_if_exists index(:categories, ["book_id"], name: "categories_book_id_index")

    drop table(:categories)
  end
end
