defmodule Terrible.Repo.Migrations.CreateBookUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:book_users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :role, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :book_id,
          references(:books,
            column: :id,
            name: "book_users_book_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "book_users_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:book_users, [:book_id, :user_id],
             name: "book_users_unique_book_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:book_users, [:book_id, :user_id],
                     name: "book_users_unique_book_user_index"
                   )

    drop constraint(:book_users, "book_users_user_id_fkey")

    drop constraint(:book_users, "book_users_book_id_fkey")

    drop table(:book_users)
  end
end
