defmodule Terrible.Repo.Migrations.ChangeCategoryReferenceStrategyForEnvelopes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:envelopes, ["category_id"], name: "envelopes_category_id_index")

    drop constraint(:envelopes, "envelopes_category_id_fkey")

    alter table(:envelopes) do
      modify :category_id,
             references(:categories,
               column: :id,
               prefix: "public",
               name: "envelopes_category_id_fkey",
               type: :uuid,
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:envelopes, "envelopes_category_id_fkey")

    alter table(:envelopes) do
      modify :category_id,
             references(:categories,
               column: :id,
               prefix: "public",
               name: "envelopes_category_id_fkey",
               type: :uuid
             )
    end

    create index(:envelopes, ["category_id"])
  end
end
