defmodule Terrible.Repo.Migrations.ChangeBudgetAndEnvelopeReferenceStrategyForMonthlyEnvelopes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:monthly_envelopes, "monthly_envelopes_envelope_id_fkey")

    drop constraint(:monthly_envelopes, "monthly_envelopes_budget_id_fkey")

    alter table(:monthly_envelopes) do
      modify :budget_id,
             references(:budgets,
               column: :id,
               prefix: "public",
               name: "monthly_envelopes_budget_id_fkey",
               type: :uuid,
               on_delete: :delete_all
             )
    end

    alter table(:monthly_envelopes) do
      modify :envelope_id,
             references(:envelopes,
               column: :id,
               prefix: "public",
               name: "monthly_envelopes_envelope_id_fkey",
               type: :uuid,
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:monthly_envelopes, "monthly_envelopes_envelope_id_fkey")

    alter table(:monthly_envelopes) do
      modify :envelope_id,
             references(:envelopes,
               column: :id,
               prefix: "public",
               name: "monthly_envelopes_envelope_id_fkey",
               type: :uuid
             )
    end

    drop constraint(:monthly_envelopes, "monthly_envelopes_budget_id_fkey")

    alter table(:monthly_envelopes) do
      modify :budget_id,
             references(:budgets,
               column: :id,
               prefix: "public",
               name: "monthly_envelopes_budget_id_fkey",
               type: :uuid
             )
    end
  end
end
