defmodule Terrible.Repo.Migrations.CreateBudgets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:budgets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text, null: false
      add :month, :naive_datetime, null: false

      add :book_id,
          references(:books,
            column: :id,
            name: "budgets_book_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create index(:budgets, ["month"])

    create unique_index(:budgets, [:book_id, :name], name: "budgets_book_budget_pair_index")
  end

  def down do
    drop_if_exists unique_index(:budgets, [:book_id, :name],
                     name: "budgets_book_budget_pair_index"
                   )

    drop constraint(:budgets, "budgets_book_id_fkey")

    drop_if_exists index(:budgets, ["month"], name: "budgets_month_index")

    drop table(:budgets)
  end
end
