defmodule Terrible.Repo.Migrations.ChangeBookReferenceStrategyForCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:categories, ["book_id"], name: "categories_book_id_index")

    drop constraint(:categories, "categories_book_id_fkey")

    alter table(:categories) do
      modify :book_id,
             references(:books,
               column: :id,
               prefix: "public",
               name: "categories_book_id_fkey",
               type: :uuid,
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:categories, "categories_book_id_fkey")

    alter table(:categories) do
      modify :book_id,
             references(:books,
               column: :id,
               prefix: "public",
               name: "categories_book_id_fkey",
               type: :uuid
             )
    end

    create index(:categories, ["book_id"])
  end
end
