defmodule Terrible.Repo.Migrations.ChangeMonthTypeFromNaiveDatetimeToDateInBudgets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:budgets) do
      modify :month, :date
    end
  end

  def down do
    alter table(:budgets) do
      modify :month, :naive_datetime
    end
  end
end
