defmodule Terrible.Repo.Migrations.CreateAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :account_type_id,
          references(:account_types,
            column: :id,
            name: "accounts_account_type_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :book_id,
          references(:books,
            column: :id,
            name: "accounts_book_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:accounts, "accounts_account_type_id_fkey")

    drop constraint(:accounts, "accounts_book_id_fkey")

    drop table(:accounts)
  end
end
