defmodule Terrible.Repo.Migrations.AddTypeToCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:categories) do
      add :type, :text, default: "standard"
    end

    create index(:categories, ["book_id", "type"], unique: true, where: "type = 'system'")
  end

  def down do
    drop_if_exists index(:categories, ["book_id", "type"], name: "categories_book_id_type_index")

    alter table(:categories) do
      remove :type
    end
  end
end
