defmodule Terrible.Repo.Migrations.CreateEnvelopes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:envelopes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text, null: false

      add :category_id,
          references(:categories,
            column: :id,
            name: "envelopes_category_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create index(:envelopes, ["category_id"])
  end

  def down do
    drop constraint(:envelopes, "envelopes_category_id_fkey")

    drop_if_exists index(:envelopes, ["category_id"], name: "envelopes_category_id_index")

    drop table(:envelopes)
  end
end
